### ISSUE TITLE
Feedback and requests 🙏

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3ui-website#6]
* [x] Scroll border not working anymore (have tried on bigger screen)
* [x] Framework toggle for code snippets needed
* [x] Example code being pulled in is too long - can we instead have a custom snippet and a link out to codesandbox?
* [x] React, Solid and Vue are shipping for Nodeconf - plz Move other “Supported frameworks” to the end of the list
* [x] Need footer implemented
* [x] Update links to React, Solid and Vue examples in navigation (leave React Native and Svelte greyed out)
* [x] Add links to new API Reference docs
* [x] We are now standardising on web3.storage (vs Web3.Storage)
* [x] Please rename “Uploads Table” to “Uploads List”
* [x] Please make look good on mobile

**Comment by cmunns** [comment]
@alanshaw would you want to provide the code snippet to me for each component/framework set?

**Comment by alanshaw** [comment]
I will, please add some placeholder code in the mean time.

**Comment by cmunns** [comment]
I've added a frameworks array to the wallet page, that should be used on the other pages as well if you want to fill in those code snippets.

**Comment by alanshaw** [comment]
https://gist.github.com/alanshaw/ce84644338cf5663f8f4923edae89ad5
